### 공연 조회
GET http://localhost:8016/api/v1/performances/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

### 공연 목록 조회(예약 가능)
GET http://localhost:8016/api/v1/performances?isReserve=enable
Content-Type: application/json

### 공연 목록 조회(예약 불가)
GET http://localhost:8016/api/v1/performances?isReserve=disable
Content-Type: application/json

### 공연 목록 조회(기본)
GET http://localhost:8016/api/v1/performances
Content-Type: application/json